# Generated by Django 3.0.8 on 2020-07-22 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('committed', models.BooleanField(default=False)),
                ('is_absent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDateTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStart', models.TimeField()),
                ('timeEnd', models.TimeField()),
                ('employeeDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.EmployeeDate')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='machine_pics')),
                ('desc', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_time', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='NonProdTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=4)),
                ('task_name', models.CharField(max_length=100)),
                ('task_desc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='machine_pics')),
                ('desc', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('machines', models.ManyToManyField(through='inprogress.MachineSetup', to='inprogress.Machine')),
                ('operators', models.ManyToManyField(through='inprogress.OperatorSetup', to='inprogress.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetEntryProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityHandled', models.IntegerField(default=0)),
                ('quantityRejected', models.IntegerField(default=0)),
                ('employee_date_time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.EmployeeDateTimeSlot')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.Machine')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.Part')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.Setup')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetEntryNonProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('employee_date_time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.EmployeeDateTimeSlot')),
                ('nonprod_task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inprogress.NonProdTask')),
            ],
        ),
        migrations.CreateModel(
            name='PartSetupSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.Part')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.Setup')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='setups',
            field=models.ManyToManyField(through='inprogress.PartSetupSequence', to='inprogress.Setup'),
        ),
        migrations.AddField(
            model_name='operatorsetup',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.Setup'),
        ),
        migrations.AddField(
            model_name='machinesetup',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inprogress.Setup'),
        ),
        migrations.AddField(
            model_name='machine',
            name='setups',
            field=models.ManyToManyField(through='inprogress.MachineSetup', to='inprogress.Setup'),
        ),
        migrations.AddField(
            model_name='employee',
            name='setups',
            field=models.ManyToManyField(through='inprogress.OperatorSetup', to='inprogress.Setup'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
