# Generated by Django 3.0.8 on 2020-07-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inprogress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonprodtask',
            old_name='task_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='nonprodtask',
            old_name='task_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='nonprodtask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
