# Generated by Django 3.0.3 on 2020-09-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inprogress', '0004_employeedate_forcecommitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedate',
            name='forceCommitted',
        ),
    ]
