# Generated by Django 3.0.3 on 2020-09-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inprogress', '0005_remove_employeedate_forcecommitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedate',
            name='forceCommitted',
            field=models.BooleanField(default=False),
        ),
    ]
