# Generated by Django 3.0.3 on 2020-09-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inprogress', '0006_employeedate_forcecommitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='id_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='machine',
            name='id_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='nonprodtask',
            name='id_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='part',
            name='id_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='setup',
            name='id_code',
            field=models.CharField(max_length=15),
        ),
    ]
