# Generated by Django 3.0.3 on 2020-09-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inprogress', '0007_auto_20200927_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='id_code',
            field=models.CharField(max_length=20),
        ),
    ]
